name: mobile
description: Flutter multiplatform app

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  core:
    path: ../../packages/core
  ui:
    path: ../../packages/ui
  routing:
    path: ../../packages/routing
  auth:
    path: ../../packages/features/auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
